# These are supported funding model platforms

# github: [YOUR_GITHUB_USERNAME] # Uncomment and replace with your GitHub username if you enable GitHub Sponsors

# buymeacoffee.com is not natively supported as a key, but you can use the custom URL list.
# common keys like ko_fi are also supported (ko_fi: username)

custom: ["https://buymeacoffee.com/jgebang"]
