"""add_answer_records_table

Revision ID: 67d632d4dd35
Revises: 8f3d2e1a9b7c
Create Date: 2026-01-23 14:04:56.462302

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67d632d4dd35'
down_revision: Union[str, Sequence[str], None] = '8f3d2e1a9b7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('answer_records',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('word', sa.String(length=100), nullable=False),
    sa.Column('part_of_speech', sa.String(length=20), nullable=True),
    sa.Column('game_type', sa.String(length=50), nullable=False),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.Column('answered_at', sa.DateTime(), nullable=False),
    sa.Column('question_type', sa.String(length=50), nullable=True),
    sa.Column('user_answer', sa.Text(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('answer_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_answer_records_answered_at'), ['answered_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_records_game_type'), ['game_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_records_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_records_part_of_speech'), ['part_of_speech'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_answer_records_word'), ['word'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('answer_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_answer_records_word'))
        batch_op.drop_index(batch_op.f('ix_answer_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_answer_records_part_of_speech'))
        batch_op.drop_index(batch_op.f('ix_answer_records_id'))
        batch_op.drop_index(batch_op.f('ix_answer_records_game_type'))
        batch_op.drop_index(batch_op.f('ix_answer_records_answered_at'))

    op.drop_table('answer_records')
    # ### end Alembic commands ###
